### ISSUE TITLE
i dont want this script to split the charecters and make huge wordlist out of small words

### ISSUE THREAD

**Issue by X3eRo0** [D4Vinci/elpscrk#2]
it would more useful if it actually just permutes the given words to form new words or add more words to the wordlist. i know cupp is exactly like i want but cupp generates very few combinations nad thats why the wordlist is too small. elpscrk is good. i just provided 4 words and you know every one got atleast 8 charecters in their password and this generated a huge file.

**Comment by D4Vinci** [comment]
Elpscrk is new tool now, check it out.

**Comment by X3eRo0** [comment]
Cool
