### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Ganofins** [D4Vinci/elpscrk#4]
File "elpscrk.py", line 35
    print "\n[!]Started at "+str(strftime("%Y-%m-%d %H:%M:%S", gmtime()))+"\n"

**Comment by sarat9** [comment]
The code works for python version 2.7.
The above error occurs when you try to use > python version 3.0.
The above is a syntax error which doesn't match with your current version.

**Comment by Ganofins** [comment]
oh that's the problem...you are right thanks
