### ISSUE TITLE
process gets randomly killed (UBNT 18.04)

### ISSUE THREAD

**Issue by r3x07** [D4Vinci/elpscrk#5]
adam@trajsec:~/mrrobot/elpscrk$ python elpscrk.py 

[!]Started at 2020-01-12 19:53:23

Info (Split It)->nigga;lod;eon

Length Of The Pwd: 8

[+]Spliting Chars....

[+]Generating Passlist ...

Killed

**Comment by D4Vinci** [comment]
Elpscrk is new tool now, check it out.
