### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by kanjiceniev** [D4Vinci/elpscrk#7]
File "elpscrk.py", line 35
    print "\n[!]Started at "+str(strftime("%Y-%m-%d %H:%M:%S", gmtime()))+"\n"
                           ^
SyntaxError: invalid syntax

**Comment by mrpotatopc** [comment]
you using python3 this is on python2 , if you are on linux then use this command and it will not crash `python ./elpscrk.py` , but if you using windows i dont know
